opt_out_usage

# Have an easy way to get the root of the project
def root_path
  Dir.pwd.sub(/.*\Kfastlane/, '').sub(/.*\Kandroid/, '').sub(/.*\Kios/, '').sub(/.*\K\/\//, '')
end

# Have an easy way to run flutter tasks on the root of the project
lane :sh_on_root do |options|
  command = options[:command]
  sh("cd #{root_path} && #{command}")
end

# Tasks to be reused on each platform flow
lane :fetch_dependencies do
  sh_on_root(command: "flutter pub get --suppress-analytics")
end

# Tasks to be reused on each platform flow
lane :build_autogenerated_code do
  sh_on_root(command: "flutter pub run build_runner build --delete-conflicting-outputs")
end

# Tasks to be reused on each platform flow
lane :lint do
  sh_on_root(command: "flutter format --suppress-analytics --set-exit-if-changed -n lib/main.dart lib/src/ test/")
end

lane :build_flutter_app do |options|
  type = options[:type]
  app_identifier_arg = options[:app_identifier]
  build_number = options[:build_number] || get_build_number(options[:store], app_identifier_arg)
  version_number = options[:version_number] || get_version_from_tag_or_pubspec()
  no_codesign = options[:no_codesign] || false
  config_only = options[:config_only] || false
  commit = last_git_commit

  # Determine environment and flavor - default to dev/production, allow override
  environment = options[:environment] || 'dev'
  flavor = options[:flavor] || 'production'
  target = options[:target]

  command = "flutter build #{type} --release --no-pub --suppress-analytics"
  command += " --flavor #{flavor}" if flavor.to_s != ""
  command += " --target #{target}" if target.to_s != ""
  command += " --build-number=#{build_number}" if build_number.to_s != ""
  command += " --build-name=#{version_number}" if version_number.to_s != ""

  # Not every flag exists on every `flutter build` subcommand, and passing one
  # that does not is a hard failure ("Could not find an option named ..."),
  # not a warning. Checked against Flutter 3.41 on Linux, where the Android
  # subcommands live:
  #
  #   apk        --config-only, no --no-codesign
  #   appbundle  neither
  #
  # ios/ipa are macOS-only so they could not be checked the same way; both
  # flags are documented for them, which is the case this gate preserves.
  ios_build = %w[ios ipa].include?(type.to_s)
  command += " --no-codesign" if no_codesign && ios_build
  command += " --config-only" if config_only && type.to_s != 'appbundle'

  if no_codesign && !ios_build
    UI.important(
      "Ignoring no_codesign: `flutter build #{type}` has no --no-codesign " \
      'flag, it is iOS-only. Android release signing comes from ' \
      'android/key.properties instead.'
    )
  end

  UI.message("Building #{type} - version: #{version_number} - build: #{build_number} - commit: #{commit[:abbreviated_commit_hash]} - env: #{environment} - flavor: #{flavor}")

  fetch_dependencies

  # Check if build_runner exists in pubspec.yaml
  # If it does, run the build_runner command
  if File.exist?("#{root_path}/pubspec.yaml")
    pubspec_content = File.read("#{root_path}/pubspec.yaml")
    if pubspec_content.include?("build_runner:")
      build_autogenerated_code
    end
  end

  sh_on_root(command: command)
end

# Tasks to be reused on each platform flow
lane :test do |options|
  sh_on_root(command: "flutter test --no-pub --coverage --suppress-analytics")
end

# Private lane to verify all environment variables are set
private_lane :verify_env do |options|
  envs = options.fetch(:envs, [])

  envs.each do |env|
    if ENV[env].nil? || ENV[env].empty?
      UI.user_error!("ENV \"#{env}\" is not set. Please set it in your environment variables (e.g. ios/fastlane/.env)")
    end
  end
end

# A helper method to get the path to the firebase service account json file
def google_service_account_json_path
  root_path + '/' + (ENV["GOOGLE_SERVICE_ACCOUNT_JSON_PATH"] || 'google_service_account.json')
end

# A helper method to get the path to the firebase service account json file
def google_firebase_service_account_json_path
  root_path + '/' + (ENV["GOOGLE_FIREBASE_SERVICE_ACCOUNT_JSON_PATH"] || 'firebase_service_account.json')
end

def get_environment_for_flavor(flavor)
  case flavor.to_s
  when 'development' then 'dev'
  when 'staging' then 'staging'
  when 'production', '' then 'prod'
  else flavor
  end
end

def get_android_aab_path(flavor = 'production')
  "#{root_path}/build/app/outputs/bundle/#{flavor}Release/app-#{flavor}-release.aab"
end

def get_android_apk_path(flavor = 'staging')
  "#{root_path}/build/app/outputs/flutter-apk/app-#{flavor}-release.apk"
end

# Build number is a unique identifier for each build that is uploaded to the app store.
# This method will get the latest build number from the app store and increment it by 1.
# Ensure authenticate_apple_store is called before this method.
# app_identifier: optional; for appstore use this bundle id (e.g. dev app); for playstore use as package name.
def get_build_number(store, app_identifier = nil)
  return get_new_build_number(
    bundle_identifier: store == "appstore" ? (app_identifier || ENV["APP_BUNDLE_ID"]) : nil,
    package_name: store == "playstore" ? (app_identifier || ENV["APP_PACKAGE_NAME"]) : nil,
    google_play_json_key_path: google_service_account_json_path
  ).to_s
end


def get_version_from_pubspec
  require 'yaml'

  pubspec_path = File.expand_path("#{root_path}/pubspec.yaml")

  unless File.exist?(pubspec_path)
    UI.error("pubspec.yaml file not found at path: #{pubspec_path}")
    return nil
  end

  pubspec_content = File.read(pubspec_path)

  version_line = pubspec_content.match(/version:\s*(\d+\.\d+\.\d+)\+(\d+)/)
  if version_line
    version_number = version_line[1]
  else
    UI.error("Version number not found in pubspec.yaml")
    return nil
  end

  return version_number
end


def get_version_from_tag_or_pubspec
  raw_tag = ENV["GITHUB_REF_NAME"]

  if raw_tag.to_s.empty?
    begin
      raw_tag = last_git_tag
    rescue StandardError
      raw_tag = nil
    end
  end

  if raw_tag.to_s != ""
    normalized = raw_tag.sub(/\Av/, "").split("-").first
    return normalized if normalized.match?(/^\d+\.\d+\.\d+$/)

    UI.message("Tag '#{raw_tag}' is not a semantic version. Falling back to pubspec.yaml version.")
  end

  get_version_from_pubspec
end
