
default_platform(:android)

platform :android do

  # Build flutter Android app
  lane :build do |options|
    verify_env(envs: [
      "APP_PACKAGE_NAME"
    ])

    # Verify version number is correct
    if !is_ci && (!options[:version_number])
      version_number = get_version_from_pubspec()
      continue = UI.confirm("Deploying version #{version_number} (from pubspec.yaml) to Play Store. Continue?")

      unless continue
        UI.user_error!("Aborted")
      end
    end

    build_flutter_app(
      type: options[:type] || "appbundle",
      no_codesign: options[:no_codesign],
      config_only: options[:config_only],
      build_number: options[:build_number],
      version_number: options[:version_number],
      store: "playstore",
      environment: options[:environment],
      flavor: options[:flavor],
      target: options[:target]
    )
  end

  # Release to Play Store using Fastlane Supply (https://docs.fastlane.tools/actions/supply/)
  desc "Release to Play Store"
  lane :release_play_store do |options|
    unless File.exist?(google_service_account_json_path)
      UI.user_error!("google_service_account.json file not found. Please add it to root of flutter project.")
    end

    begin
      build(
        no_codesign: options[:no_codesign],
        config_only: options[:config_only],
        build_number: options[:build_number],
        version_number: options[:version_number],
        environment: 'prod',  # Production for Play Store releases
        flavor: 'production',
        target: 'lib/main_production.dart'
      )

      aab_path = get_android_aab_path('production')
      unless File.exist?(aab_path)
        UI.user_error!("Could not find AAB artifact at '#{aab_path}'.")
      end

      supply(
        track: 'internal',
        # Uncomment this if getting error "Only releases with status draft may be created on draft app."
        release_status: 'draft',
        aab: aab_path,
        json_key: google_service_account_json_path,
        skip_upload_apk: true, # Upload aab instead of apk
        skip_upload_metadata: true,
        skip_upload_changelogs: true,
        skip_upload_images: true,
        skip_upload_screenshots: true
      )
    end
  end

  # Release to Firebase App Distribution (staging builds)
  desc "Distribute to Firebase App Distribution"
  lane :release_firebase_app_distribution do |options|
    verify_env(envs: ["FIREBASE_APP_ID_ANDROID_STAGING"])

    build(
      type: 'apk',
      no_codesign: options[:no_codesign],
      config_only: options[:config_only],
      build_number: options[:build_number],
      version_number: options[:version_number],
      environment: 'staging',
      flavor: 'staging',
      target: 'lib/main_staging.dart'
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_ANDROID_STAGING"],
      android_artifact_path: get_android_apk_path('staging'),
      service_credentials_file: google_firebase_service_account_json_path,
      release_notes: release_notes_or_last_commit(options[:release_notes]),
      groups: options[:groups] || "qa-testers",
      debug: true
    )
  end
end
